libc_a_SOURCES =  %D%/accept.c %D%/bind.c %D%/chdir.c %D%/close.c %D%/closedir.c %D%/connect.c %D%/dirname.c \
            %D%/dup2.c %D%/dup.c %D%/errno.c %D%/exec.c %D%/exit.c %D%/fgets.c %D%/free.c %D%/fcntl.c \
            %D%/getaddrinfo.c %D%/getcwd.c %D%/gethostname.c %D%/getlogin.c %D%/getpeername.c %D%/getpid.c \
            %D%/getppid.c %D%/getpriority.c %D%/getsockname.c %D%/getsockopt.c %D%/gettimeofday.c \
            %D%/grp.c %D%/inet.c %D%/ioctl.c %D%/isatty.c %D%/kill.c %D%/link.c \
            %D%/listen.c %D%/lseek.c %D%/malloc.c %D%/malloc_trim.c %D%/mkdir.c %D%/mount.c \
            %D%/mutex.c %D%/mutex_init.c %D%/open.c %D%/opendir.c %D%/pipe.c %D%/poll.c %D%/printf.c \
            %D%/pthread.c %D%/ptrace.c %D%/pty.c %D%/pwd.c %D%/read.c %D%/readdir.c %D%/reboot.c \
            %D%/recvfrom.c %D%/resource.c %D%/sched.c %D%/select.c %D%/semaphore.c %D%/sem_init.c %D%/sendto.c \
            %D%/setpriority.c %D%/setsid.c %D%/setsockopt.c %D%/shutdown.c %D%/sigaction.c %D%/signal.c \
            %D%/sigprocmask.c %D%/sigsuspend.c %D%/sleep.c %D%/socket.c %D%/stat.c %D%/svc.S \
            %D%/syscall.c %D%/syscalls.c %D%/tcgetattr.c %D%/tcsendbreak.c %D%/tcsetattr.c %D%/truncate.c \
            %D%/ttyname.c %D%/uid.c %D%/umask.c %D%/umount.c %D%/unlink.c %D%/uname.c \
            %D%/vfork.c %D%/wait.c %D%/waitpid.c %D%/write.c %D%/stubs.c %D%/readlink.c \
            %D%/realpath.c



